name: Build Windows

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a release'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.41.0

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Windows
        run: |
          flutter build windows --release --dart-define-from-file env/prod.json -t lib/main.dart -v

      - name: Package Windows build
        shell: pwsh
        run: |
          $version = (Select-String -Pattern 'version: (.+)' pubspec.yaml | ForEach-Object { $_.Matches[0].Groups[1].Value })
          $appname = (Select-String -Pattern 'name: (.+)' pubspec.yaml | ForEach-Object { $_.Matches[0].Groups[1].Value })
          $zipName = "$appname-$version-windows.zip"
          $releaseDir = "build/windows/x64/runner/Release"
          
          # Create zip file
          Compress-Archive -Path $releaseDir -DestinationPath $zipName -Force
          Write-Host "Packaged Windows build: $zipName"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: |
            *.zip

      - name: Create Release
        if: github.event.inputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
          draft: true
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
